blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, switch_publish_status, BlogCreateView, BlogUpdateView, \
    BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<str:slug>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/switch/<int:pk>/', switch_publish_status, name='switch_publish_status'),
    path('blog/delete/<str:slug>', BlogDeleteView.as_view(), name='blog_delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models/blogs.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify
from unidecode import unidecode

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    heading = models.CharField(max_length=250, verbose_name='heading', unique=True)
    slug = models.CharField(max_length=250, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='content')
    img = models.ImageField(upload_to='blog/', verbose_name='preview')
    created = models.DateTimeField(auto_now_add=True, verbose_name='creation date')
    is_published = models.BooleanField(default=True, verbose_name='is_published')
    views = models.IntegerField(verbose_name='views number', default=0, **NULLABLE)

    def __str__(self):
        return f'{self.heading} {self.slug}'

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.heading))
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.is_published = False
        self.save()

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'
        permissions = [
            (
                'set_published',
                'can publish/unpublish'
            )
        ]

blog/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from blog.models import Blog
from blog.services import send_email_hundred_views


class BlogListView(generic.ListView):
    model = Blog
    extra_context = {'page_title': 'Blogs'}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(generic.DetailView):
    model = Blog

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['page_title'] = 'Blog details'

        self.object.views += 1
        self.object.save()

        if self.object.views == 100:
            send_email_hundred_views()

        return context_data


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = Blog
    fields = ('heading', 'content', 'img', 'is_published')
    permission_required = 'blog.add_blog'

    def get_success_url(self):
        return reverse_lazy('blog:blog_detail', kwargs={'slug': self.object.slug})


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = Blog
    fields = ('heading', 'content', 'img', 'is_published')
    permission_required = 'blog.change_blog'

    def get_success_url(self):
        return reverse_lazy('blog:blog_detail', kwargs={'slug': self.object.slug})


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')
    permission_required = 'blog.delete_blog'


@permission_required('blog.set_published', raise_exception=True)
def switch_publish_status(request, pk):

    blog_object = get_object_or_404(Blog, pk=pk)

    if blog_object.is_published:
        blog_object.is_published = False
    else:
        blog_object.is_published = True

    blog_object.save()

    slug = blog_object.slug
    return redirect(reverse('blog:blog_detail', kwargs={'slug': slug}))

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html'%}
{% load static %}
{% block content %}

<main class="container">
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="col-lg-6 px-0">
            <h1 class="display-2 fst-italic">Deleting confirmation</h1><br><br>
        </div>
        <form method="post">
            {% csrf_token %}
            <h2>Are you sure that you want to delete the '{{object.heading}}' blog?</h2>
            <input type="submit" class="btn btn-warning" value="Yes">
        </form>
    </div>
</main>
{% endblock%}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html'%}
{% load static %}
{% block content %}

<main class="container">
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="col-lg-6 px-0">
            <h1 class="display-2 fst-italic">{{object.heading}}</h1><br><br>
        </div>


        <article class="blog-post">

            <p class="blog-post-meta">{{object.created}}</p>
            <p>{{object.content}}</p>

        </article>

        <nav>
            <a class="btn btn-outline-danger rounded-pill float-end"
               role=button href="{% url 'blog:blog_delete' object.slug %}">Delete</a>
            <a class="btn btn-outline-info rounded-pill float-end"
               role=button href="{% url 'blog:blog_update' object.slug %}">Edit</a>
            <a class="btn btn-outline-primary rounded-pill" href="{% url 'blog:blog_list' %}">Back</a>
            <a class="btn btn-outline-warning rounded-pill float-end"
               role=button href="{% url 'blog:switch_publish_status' object.pk %}">
                {% if object.is_published %}
                Unpublish
                {% else %}
                Publish
                {% endif %}
            </a>

        </nav>

    </div>
</main>
{% endblock%}

blog/templates/blog/blog_form.html
{% extends 'main/base.html'%}
{% load static %}
{% block content %}

<main class="container">
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
        <h1>Input the blog's details</h1>
        <br>
        <form method="post" enctype="multipart/form-data" class="form-control row g-3 mb-3">
            {% csrf_token %}
            {{ form.as_p }}
            <div>
                <button type="submit" class="btn btn-primary">

                    {% if object %}
                    Save
                    {% else %}
                    Create
                    {% endif %}
                </button>
            </div>
        </form>
    </div>
</main>
{% endblock%}

blog/templates/blog/blog_list.html
{% extends 'main/base.html'%}
{% block content %}
{% load my_tags%}

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Blogs Segment</h1>
                <p class="lead text-body-secondary">Here is the list of blogs</p>
                <p>
                    <a href="{% url 'blog:blog_create' %}" class="btn btn-success my-2">Create a blog</a>
                </p>
            </div>
        </div>
    </section>


    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

                {% for object in object_list%}
                <div class="col-lg-4">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <img src="{% mediapath object.img %}" class="img-thumbnail" alt="">
                            <p class="card-text">{{object.heading}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'blog:blog_detail' object.slug %}"
                                       class="btn btn-secondary">Details</a>
                                </div>
                                <small class="text-body-secondary">{{object.views}} views</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>


</main>
{% endblock%}