blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, switch_publish_status, BlogCreateView, BlogUpdateView, \
    BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<str:slug>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/switch/<int:pk>/', switch_publish_status, name='switch_publish_status'),
    path('blog/delete/<str:slug>', BlogDeleteView.as_view(), name='blog_delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, verify_email, restore_user, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/verification/<str:email>', verify_email, name='verify_email'),
    path('login/restore/', restore_user, name='restore_user'),
    path('profile/', ProfileView.as_view(), name='profile')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from blog.models.blogs import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='user_email')
    avatar = models.ImageField(upload_to='avatar/', verbose_name='user_avatar', **NULLABLE)
    phone = models.CharField(max_length=40, verbose_name='user_phone', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='user_country', **NULLABLE)
    verification_code = models.CharField(verbose_name='email_verification_code', **NULLABLE)
    is_email_verified = models.BooleanField(verbose_name='is_email_verified', default=False, **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from main.forms import FormStyleMixin
from users.models import User


class RegisterForm(FormStyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class ProfileForm(FormStyleMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'avatar', 'phone', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from users.forms import RegisterForm, ProfileForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['page_title'] = 'Log in'
        return context_data


class LogoutView(BaseLogoutView):
    pass


class RegisterView(generic.CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        self.object = form.save()
        if form.is_valid():
            code = ''.join([str(random.randint(0, 9)) for _ in range(12)])
            self.object.verification_code = code
            self.object.save()
            send_mail(
                'email verification',
                f'Your password - {code}',
                settings.EMAIL_HOST_USER,
                [self.object.email]
            )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('users:verify_email', kwargs={'email': self.object.email})

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['page_title'] = 'Register'
        return context_data


class ProfileView(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = ProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['page_title'] = 'Profile'
        return context_data


def verify_email(request, email):
    if request.method == 'POST':
        code_to_check = request.POST.get('verification_code')
        user = User.objects.get(email=email)
        if user.verification_code == code_to_check:
            user.is_email_verified = True
            user.save()
            return redirect(reverse('users:login'))
        else:
            raise ValidationError(f'You have used the wrong code!')
    else:
        context = {'page_title': 'Email verification'}
        return render(request, 'users/verify_email.html', context)


def restore_user(request):
    if request.method == 'POST':
        email = request.POST.get('user_email')
        user = User.objects.get(email=email)
        new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        send_mail(
            'email verification',
            f'Your new password - {new_password}. Use it for logging in.',
            settings.EMAIL_HOST_USER,
            [user.email]
        )
        user.set_password(new_password)
        user.save()
        return redirect(reverse('users:login'))
    else:
        context = {'page_title': 'Restore user'}
        return render(request, 'users/restore_password.html', context)

users/templates/users/login.html
{% extends 'main/base.html'%}
{% block content %}
<br><br><br>

<div class="col-12">

    <form class="row" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>Login</h3>
                </div>
                <div class="card-body">
                    {{ form.as_p}}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Login</button>
                    <a href="{% url 'users:restore_user'%}" class="float-end">Forget password</a>
                </div>

            </div>

        </div>

    </form>
</div>

{% endblock %}

users/templates/users/login_warning.html
{% extends 'main/base.html'%}
{% block content %}
<br><br><br>

<div class="col-12">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>Log in issue</h3>
                </div>
                <div class="card-body">
                  <h5>You have to log in first</h5>
                </div>
                <div class="card-footer">
                    <a class="btn btn-primary" href="{% url 'users:login' %}">Log in</a>
                </div>
            </div>

        </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html'%}
{% block content %}
<br><br><br>

<div class="col-12">

    <form class="row" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>Register</h3>
                </div>
                <div class="card-body">
                    {{ form.as_p}}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </div>

        </div>

    </form>
</div>

{% endblock %}

users/templates/users/restore_password.html
{% extends 'main/base.html'%}
{% block content %}
<br><br><br>

<div class="col-12">

    <form class="row" method="post">
        {% csrf_token %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>User restoration</h3>
                </div>
                <div class="card-body">
                    <div class="col-auto">
                        <label for="inputPassword6" class="col-form-label">Input email here:</label>
                    </div>
                    <div class="col-auto">
                        <input type="text" id="inputPassword6" class="form-control"
                               aria-labelledby="passwordHelpInline" name="user_email">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Get a new password</button>
                </div>
            </div>

        </div>

    </form>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html'%}
{% block content %}
<br><br><br>

<div class="col-12">

    <form class="row" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>Change profile</h3>
                </div>
                <div class="card-body">
                    {{ form.as_p}}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>

        </div>

    </form>
</div>

{% endblock %}

users/templates/users/verify_email.html
{% extends 'main/base.html'%}
{% block content %}
<br><br><br>

<div class="col-12">

    <form class="row" method="post">
        {% csrf_token %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>Email verification</h3>
                </div>
                <div class="card-body">
                    <div class="col-auto">
                        <label for="inputPassword6" class="col-form-label">Input your code from email here:</label>
                    </div>
                    <div class="col-auto">
                        <input type="text" id="inputPassword6" class="form-control"
                               aria-labelledby="passwordHelpInline" name="verification_code">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Check the code</button>
                </div>
            </div>

        </div>

    </form>
</div>

{% endblock %}