blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, switch_publish_status, BlogCreateView, BlogUpdateView, \
    BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<str:slug>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/switch/<int:pk>/', switch_publish_status, name='switch_publish_status'),
    path('blog/delete/<str:slug>', BlogDeleteView.as_view(), name='blog_delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import PromoOneView, PromoTwoView, ProductListView, ProductCreateView, ProductDetailView, \
    ProductUpdateView, ProductDeleteView, make_unpublished

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='add'),
    path('product/<str:slug>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/unpublish/<str:slug>/', make_unpublished, name='make_unpublished'),
    path('product/update/<str:slug>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<str:slug>/', ProductDeleteView.as_view(), name='product_delete'),
    path('promo_one/', cache_page(60)(PromoOneView.as_view()), name='promo_one'),
    path('promo_two/', cache_page(60)(PromoTwoView.as_view()), name='promo_two')
]

main/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):
    id = models.AutoField(primary_key=True, verbose_name='prod_id')
    name = models.CharField(max_length=100, verbose_name='prod_name')
    description = models.TextField(verbose_name='prod_descr', **NULLABLE)
    price = models.IntegerField(verbose_name='prod_price')
    stock = models.IntegerField(verbose_name='prod_stock')
    img = models.ImageField(upload_to='media/', verbose_name='product_img')

    def __str__(self):
        return f'{self.id} {self.name}'

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

main/models/category.py
from django.db import models
from django.utils.text import slugify
from unidecode import unidecode

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    category_name = models.CharField(max_length=250, verbose_name='category_name', unique=True)
    slug = models.SlugField(verbose_name='slug', **NULLABLE)
    category_description = models.TextField(verbose_name='category_description', **NULLABLE)
    is_active = models.BooleanField(verbose_name='is_active', default=True)

    def __str__(self):
        return f'{self.category_name}'

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.category_name))
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

main/models/products.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from unidecode import unidecode

from main.models.category import Category

NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='prod_name', unique=True)
    slug = models.SlugField(verbose_name='slug', **NULLABLE)
    description = models.TextField(verbose_name='prod_descr', **NULLABLE)
    img = models.ImageField(upload_to='media/', verbose_name='product_img')
    is_active = models.BooleanField(verbose_name='is_active', **NULLABLE, default=True)
    user_product = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                                     verbose_name='user')
    is_published = models.BooleanField(verbose_name='is_published', default=False, **NULLABLE)
    category_product = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='category_product',
                                         **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.name))
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        permissions = [
            ('set_published',
             'can publish/make unpublished'
             )
        ]

main/models/version.py
from django.db import models

from main.models import Product

NULLABLE = {'null': True, 'blank': True}


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='product_name',
                                related_name='versions')
    name = models.CharField(max_length=100, verbose_name='version_name')
    description = models.TextField(verbose_name='version_descr', **NULLABLE)
    price = models.IntegerField(verbose_name='version_price')
    stock = models.IntegerField(verbose_name='version_stock')
    is_active = models.BooleanField(verbose_name='is_active')

    def __str__(self):
        return f'{self.name} {self.price}'

    def save(self, *args, **kwargs):
        if self.is_active:
            for version in self.product.versions.all():
                if version.is_active and version is not self:
                    version.is_active = False
                    version.save()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'version'
        verbose_name_plural = 'versions'

main/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError

from main.models import Product, Version


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('user_product', )

    def clean_name(self):
        prohibited_names = [
            'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар',
            'casino', 'cryptocurrency', 'crypto', 'exchange', 'cheap', 'free', 'fraud', 'police', 'radar'
        ]

        cleaned_data = self.cleaned_data['name']
        cleaned_data_lower = cleaned_data.lower()
        for word in prohibited_names:
            match = re.search(word, cleaned_data_lower)
            if match:
                raise ValidationError('Don\'t use prohibited words for the product\'s name!')

        return cleaned_data


class VersionForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_active':
                self.fields[field_name] = forms.BooleanField(
                    required=False, widget=forms.CheckboxInput(attrs={'class': 'checkbox-small'}), label=field_name
                )

main/views.py
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views import generic

from main.forms import ProductForm, VersionForm
from main.models import Product, Version
from main.services import get_products_active


class ProductListView(LoginRequiredMixin, generic.ListView):
    model = Product
    paginate_by = 3
    ordering = 'pk'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Main page'
        return context

    def get_queryset(self, *args, **kwargs):
        if settings.CACHE_ENABLED:
            key = 'prod_list'
            prod_list = cache.get(key)
            if prod_list is None:
                queryset = super().get_queryset(*args, **kwargs)
                prod_list = get_products_active(queryset)
                cache.set(key, prod_list)
            print('Cached data is used')
            return prod_list
        else:
            queryset = super().get_queryset(*args, **kwargs)
            prod_list = get_products_active(queryset)
            print('DB data is used')
        return prod_list


class ProductDetailView(LoginRequiredMixin, generic.DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('main:product_list')
    extra_context = {
        'page_title': 'Add a product'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST)
        else:
            context_data['formset'] = VersionFormset()
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        self.object.user_product = self.request.user
        self.object.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        else:
            print(formset.errors)
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        group = Group.objects.get(name="moderator")
        if not self.request.user.groups.filter(name=group).exists():
            permission = Permission.objects.get(codename="change_product")
            self.request.user.user_permissions.remove(permission)
            self.request.user.save()
        return reverse('main:product_detail', args=[self.kwargs.get('slug')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        if not self.request.user.has_perm('main.change_product') and self.request.user != self.object.user_product:
            raise Http404('You can\'t edit product that have not been added by you!')
        elif not self.request.user.has_perm('main.change_product') and self.request.user == self.object.user_product:
            content_type = ContentType.objects.get_for_model(Product)
            permissions = Permission.objects.get(
                codename="change_product",
                content_type=content_type
            )
            self.request.user.user_permissions.add(permissions)
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        else:
            print(formset.errors)
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('main:product_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        if self.object.user_product != self.request.user:
            raise Http404('This is not your product! You can only delete product that have been added by you.')

        return self.object


@permission_required('main.set_published')
def make_unpublished(request, slug):
    if not request.user.has_perm('main.set_published'):
        raise Http404('set_published_product permission is needed!')
    product = Product.objects.get(slug=slug)
    product.is_published = not product.is_published
    product.save()
    return redirect(reverse('main:product_detail', kwargs={'slug': slug}))


class PromoOneView(generic.TemplateView):
    template_name = 'main/promo_page_1.html'
    extra_context = {
        'page_title': 'Promo one'
    }


class PromoTwoView(generic.TemplateView):
    template_name = 'main/promo_page_2.html'
    extra_context = {
        'page_title': 'Promo two'
    }

main/templates/main/add_product.html
{% extends 'main/base.html'%}
{% block content %}
<h1>Add a new product here.</h1>
<h2>Fill in the fields bellow:</h2>
<br><br><br>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm">Name</span>
        <input type="text" name="name" class="form-control" aria-label="Sizing example input"
               aria-describedby="inputGroup-sizing-sm" required>
    </div>
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm">Description</span>
        <textarea class="form-control" name="description" aria-label="Sizing example input"
                  aria-describedby="inputGroup-sizing-sm"></textarea>

    </div>
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm">Price</span>
        <input type="text" class="form-control" name="price" aria-label="Sizing example input"
               aria-describedby="inputGroup-sizing-sm" required>
    </div>
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm">Stock</span>
        <input type="text" class="form-control" name="stock" aria-label="Sizing example input"
               aria-describedby="inputGroup-sizing-sm" required>
    </div>
    <div class="mb-3">
        <input class="form-control" type="file" id="formFile" name="img" required>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>


{% endblock %}

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>{{page_title|title}}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }




    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
</head>
<body>

{% include 'main/includes/inc_main_menu_and_carousel.html' %}

<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
        {% block content %}
        {% endblock %}
    </div><!-- /.row -->
</div><!-- /.container -->


<!-- FOOTER -->
<footer class="container">
    <br><br>
    <p class="float-end">&copy; 2022–{% now 'Y' %} Company, Inc.</p>
</footer>
</main>


<script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>

</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html'%}
{% block content%}
{% load my_tags %}
{% for product in page_obj%}
<div class="col-lg-4">
    <img src="{% mediapath product.img %}" class="img-thumbnail" alt="">
    <h2 class="fw-normal">{{product.name|title}}</h2>
    <p>{{product.description|text_limit_to_display}}</p>
    <p>Stock - {{product.stock}}</p>
    <p>Price - {{product.price}}</p>
    <div class="btn-group">
        <button type="button" class="btn btn-secondary btn-lg">Buy</button>
    </div>
</div><!-- /.col-lg-4 -->
{% endfor %}

<nav aria-label="Page navigation example">
    <br><br><br>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
        <li class="page-item {% if num == page_obj.number %}active{% endif %}"><a class="page-link"
                                                                                  href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html'%}
{% load static %}
{% block content %}

<main class="container">
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="col-lg-6 px-0">
            <h1 class="display-2 fst-italic">Deleting confirmation</h1><br><br>
        </div>
        <form method="post">
            {% csrf_token %}
            <h2>Are you sure that you want to delete the '{{object.heading}}' product?</h2>
            <input type="submit" class="btn btn-warning" value="Yes">
        </form>
    </div>
</main>
{% endblock%}

main/templates/main/product_detail.html
{% extends 'main/base.html' %}

{% block content %}

<div class="card col-4">
    <img src="{{ product.img.url }}" class="card-img-top" alt="The product's image">
    <div class="card-body">
        <h5 class="card-title">{{ object.name}}</h5>
        <p class="card-text">{{ object.description}}</p>
        <p class="card-text">Author - {{ object.user_product }}</p>
        <p>Category - {{ object.category_product }}</p>
        <p class="card-text">
            {% for version in object.versions.all %}
            {% if version.is_active %}
            Actual version - {{ version.name }}
            {% endif %}
            {% endfor %}
        </p>

    </div>

    <div class="card-body">
        {% if perms.main.change_product %}
            <a href="{% url 'main:product_update' object.slug %}" class="btn btn-outline-info">Edit</a>
            {% if user == object.user_product %}
                <a href="{% url 'main:product_delete' object.slug %}" class="btn btn-outline-danger">Delete</a>
            {% else %}
                <a href="{% url 'main:product_delete' object.slug %}" class="btn btn-outline-secondary disabled">Delete</a>
            {% endif %}
            {% if object.is_published %}
                <a href="{% url 'main:make_unpublished' object.slug %}" class="btn btn-outline-warning">Unpublish</a>
            {% else %}
                <a href="{% url 'main:make_unpublished' object.slug %}" class="btn btn-outline-success">Publish</a>
            {% endif %}
        {% else %}
            {% if user == object.user_product %}
                <a href="{% url 'main:product_update' object.slug %}" class="btn btn-outline-info">Edit</a>
                <a href="{% url 'main:product_delete' object.slug %}" class="btn btn-outline-danger">Delete</a>
            {% else %}
                <a href="{% url 'main:product_update' object.slug %}" class="btn btn-outline-secondary disabled">Edit</a>
                <a href="{% url 'main:product_delete' object.slug %}" class="btn btn-outline-secondary disabled">Delete</a>
            {% endif %}
        {% endif %}
    </div>
</div>

{% endblock %}

main/templates/main/product_form.html
{% extends 'main/base.html'%}
{% block content %}
<br><br><br>
<h1>{% if object %}Edit product{% else%} Add a new product here{% endif %}</h1>


<div class="col-12">

    <form class="row" method="post" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>Fill in info about the product</h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p}}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">{% if object %}Save{% else%}Add{% endif %}</button>
                </div>
            </div>

        </div>

        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h3>Fill in info about the product's version</h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p}}
                    {% if not forloop.last %}
                    <div class="card-footer">
                        <br>
                    </div>
                    {% endif %}
                    {% endfor%}
                </div>
                <div class="card-footer">
                    <br>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

main/templates/main/product_list.html
{% extends 'main/base.html'%}
{% block content %}
{% load my_tags %}
<main>

    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true"
                    aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <rect width="100%" height="100%" fill="#777"/>
                </svg>

                <div class="container">
                    <div class="carousel-caption text-start">
                        <h1>The Best e-store ever.</h1>
                        <p>The Best e-Store ever description.</p>
                        <p>More about The Best e-Store ever.</p>
                        <p>The Best e-Store ever slogan.</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <rect width="100%" height="100%" fill="#777"/>
                </svg>

                <div class="container">
                    <div class="carousel-caption">
                        <h1>The Best e-store ever Promo Campaign.</h1>
                        <p>Promo Campaign description</p>
                        <p>Promo Campaign description</p>
                        <p><a class="btn btn-lg btn-primary" href="{% url 'main:promo_one'%}">Learn more</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <rect width="100%" height="100%" fill="#777"/>
                </svg>

                <div class="container">
                    <div class="carousel-caption text-end">
                        <h1>The Best e-store ever Promo Campaign 2.</h1>
                        <p>Promo Campaign description</p>
                        <p>Promo Campaign description</p>
                        <p><a class="btn btn-lg btn-primary" href="{% url 'main:promo_two'%}">Learn more</a></p>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</main>

{% for product in page_obj %}
<div class="col-lg-4">
    {% if product.is_published %}
    <img src="{% mediapath product.img %}" class="img-thumbnail" alt="">
    <h2 class="fw-normal">{{ product.name|title }}</h2>
    <p>{{ product.description|text_limit_to_display }}</p>
    <p>Category - {{ product.category_product }}</p>
    <p>{% for version in product.versions.all %}
        {% if version.is_active %}
        Actual version - {{ version.name }}
        {% endif %}
        {% endfor %}
    </p>
    <p class="card-text">Author - {{ product.user_product }}</p>
    <div class="btn-group">
        <a type="button" class="btn btn-secondary btn-lg" href="{% url 'main:product_detail' product.slug %}">Go to
            product</a>
    </div>
    {% endif %}
</div><!-- /.col-lg-4 -->
{% endfor %}

<nav aria-label="Page navigation example">
    <br><br><br>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% for page_number in page_obj.paginator.page_range %}
        <li class="page-item {% if page_number == page_obj.number %}active{% endif %}">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

main/templates/main/promo_page_1.html
{% extends 'main/base.html' %}
{% block content %}

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">The Best promo</h5>
    <p class="card-text">The Best promo description.</p>
    <p class="card-text">The Best promo description.</p>
  </div>
</div>

{% endblock %}

main/templates/main/promo_page_2.html
{% extends 'main/base.html' %}
{% block content %}

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">The Best promo</h5>
    <p class="card-text">The Best promo description.</p>
    <p class="card-text">The Best promo description.</p>
  </div>
</div>

{% endblock %}